[package]
name = "pairstat_pybind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pairstat_pybind"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
pairstat = { git = "https://github.com/mabruzzo/pairstat-rs.git", revision = "dd31367ead2f361b40e85e2a1b1d26fb343d5c9f" }
